// final url = 'http://192.168.137.1:3000/';
// const url = 'http://192.168.1.110:3000/';
const url = 'http://localhost:3000/';
final registration = url + "registration";
final login = url + 'login';
final insert = url + 'inserttest';
// final addtodo = url + 'storeTodo';
// final getToDoList = url + 'getUserTodoList';
// final deleteTodo = url + 'deleteTodo';
